// Mock catalogue parts for development. Replace with Supabase data once wired.
// Realistic NZ joinery hardware: SKUs, pricing (30% markup on cost), proper fits/fixes tags.
// cost_price = what he pays (ex GST). sell_price = cost * 1.30.
// photo_url is null until Supabase storage is set up -- UI shows a letter placeholder.

export const MOCK_PARTS = [
  {
    id: 'part-001',
    sku: 'DR-220',
    name: 'Sliding door roller pair',
    supplier: 'Joinery Hardware NZ',
    supplier_code: 'JHN-DR220',
    cost_price: 18.00,
    sell_price: 23.40,
    category: 'rollers',
    fits: ['sliding_door'],
    fixes: ['stiff'],
    default_qty: 2,
    photo_url: null,
    unit: 'pair',
    active: true,
  },
  {
    id: 'part-002',
    sku: 'DR-225',
    name: 'Heavy duty sliding door roller',
    supplier: 'Joinery Hardware NZ',
    supplier_code: 'JHN-DR225',
    cost_price: 24.50,
    sell_price: 31.85,
    category: 'rollers',
    fits: ['sliding_door'],
    fixes: ['stiff'],
    default_qty: 2,
    photo_url: null,
    unit: 'each',
    active: true,
  },
  {
    id: 'part-003',
    sku: 'SL-114',
    name: 'Sliding door latch lock',
    supplier: 'Joinery Hardware NZ',
    supplier_code: 'JHN-SL114',
    cost_price: 22.00,
    sell_price: 28.60,
    category: 'locks',
    fits: ['sliding_door'],
    fixes: ['wont_lock'],
    default_qty: 1,
    photo_url: null,
    unit: 'each',
    active: true,
  },
  {
    id: 'part-004',
    sku: 'SH-300',
    name: 'Sliding door handle set',
    supplier: 'Joinery Hardware NZ',
    supplier_code: 'JHN-SH300',
    cost_price: 35.00,
    sell_price: 45.50,
    category: 'handles',
    fits: ['sliding_door'],
    fixes: ['broken_hardware'],
    default_qty: 1,
    photo_url: null,
    unit: 'set',
    active: true,
  },
  {
    id: 'part-005',
    sku: 'WS-200',
    name: 'Sliding door weatherseal',
    supplier: 'Joinery Hardware NZ',
    supplier_code: 'JHN-WS200',
    cost_price: 12.00,
    sell_price: 15.60,
    category: 'seals',
    fits: ['sliding_door'],
    fixes: ['drafty'],
    default_qty: 1,
    photo_url: null,
    unit: 'metre',
    active: true,
  },
  {
    id: 'part-006',
    sku: 'ST-400',
    name: 'Friction stay 400mm',
    supplier: 'Joinery Hardware NZ',
    supplier_code: 'JHN-ST400',
    cost_price: 28.00,
    sell_price: 36.40,
    category: 'stays',
    fits: ['window_ali'],
    fixes: ['broken_hardware'],
    default_qty: 1,
    photo_url: null,
    unit: 'each',
    active: true,
  },
  {
    id: 'part-007',
    sku: 'ST-300',
    name: 'Friction stay 300mm',
    supplier: 'Joinery Hardware NZ',
    supplier_code: 'JHN-ST300',
    cost_price: 22.00,
    sell_price: 28.60,
    category: 'stays',
    fits: ['window_ali', 'window_timber'],
    fixes: ['broken_hardware'],
    default_qty: 1,
    photo_url: null,
    unit: 'each',
    active: true,
  },
  {
    id: 'part-008',
    sku: 'WL-210',
    name: 'Aluminium window latch',
    supplier: 'Joinery Hardware NZ',
    supplier_code: 'JHN-WL210',
    cost_price: 16.50,
    sell_price: 21.45,
    category: 'locks',
    fits: ['window_ali'],
    fixes: ['wont_lock'],
    default_qty: 1,
    photo_url: null,
    unit: 'each',
    active: true,
  },
  {
    id: 'part-009',
    sku: 'BH-400',
    name: 'Bifold door hinge pair',
    supplier: 'Joinery Hardware NZ',
    supplier_code: 'JHN-BH400',
    cost_price: 32.00,
    sell_price: 41.60,
    category: 'hinges',
    fits: ['bifold_door'],
    fixes: ['broken_hardware', 'stiff'],
    default_qty: 2,
    photo_url: null,
    unit: 'pair',
    active: true,
  },
  {
    id: 'part-010',
    sku: 'BG-120',
    name: 'Bifold door guide track',
    supplier: 'Joinery Hardware NZ',
    supplier_code: 'JHN-BG120',
    cost_price: 28.00,
    sell_price: 36.40,
    category: 'rollers',
    fits: ['bifold_door'],
    fixes: ['stiff', 'misaligned'],
    default_qty: 1,
    photo_url: null,
    unit: 'each',
    active: true,
  },
  {
    id: 'part-011',
    sku: 'HH-500',
    name: 'Hinged door hinge pair',
    supplier: 'Joinery Hardware NZ',
    supplier_code: 'JHN-HH500',
    cost_price: 18.00,
    sell_price: 23.40,
    category: 'hinges',
    fits: ['hinged_door'],
    fixes: ['broken_hardware', 'stiff'],
    default_qty: 2,
    photo_url: null,
    unit: 'pair',
    active: true,
  },
  {
    id: 'part-012',
    sku: 'HL-310',
    name: 'Door latch and striker plate',
    supplier: 'Joinery Hardware NZ',
    supplier_code: 'JHN-HL310',
    cost_price: 24.00,
    sell_price: 31.20,
    category: 'locks',
    fits: ['hinged_door'],
    fixes: ['wont_lock'],
    default_qty: 1,
    photo_url: null,
    unit: 'set',
    active: true,
  },
  {
    id: 'part-013',
    sku: 'WH-150',
    name: 'Window handle',
    supplier: 'Joinery Hardware NZ',
    supplier_code: 'JHN-WH150',
    cost_price: 19.50,
    sell_price: 25.35,
    category: 'handles',
    fits: ['window_ali', 'window_timber'],
    fixes: ['broken_hardware'],
    default_qty: 1,
    photo_url: null,
    unit: 'each',
    active: true,
  },
  {
    id: 'part-014',
    sku: 'WS-305',
    name: 'Window weatherseal strip',
    supplier: 'Joinery Hardware NZ',
    supplier_code: 'JHN-WS305',
    cost_price: 9.50,
    sell_price: 12.35,
    category: 'seals',
    fits: ['window_ali', 'window_timber', 'sliding_door'],
    fixes: ['drafty'],
    default_qty: 1,
    photo_url: null,
    unit: 'metre',
    active: true,
  },
  {
    id: 'part-015',
    sku: 'BL-220',
    name: 'Bifold door lock set',
    supplier: 'Joinery Hardware NZ',
    supplier_code: 'JHN-BL220',
    cost_price: 38.00,
    sell_price: 49.40,
    category: 'locks',
    fits: ['bifold_door'],
    fixes: ['wont_lock'],
    default_qty: 1,
    photo_url: null,
    unit: 'set',
    active: true,
  },
]
